Refactor. 파일 업로드 서버 연결 및 잡일
KrossCutting/KrossCutting-client pull request #12
Opened 2024-02-13 10:29 UTC by sht02048

# 관련 KanBan Title
- [랜딩 페이지](https://minsug.notion.site/Client-f04cab7d28fe42eb9a667be26806d649?pvs=4)

# Tasks in detail - checkList
- [x] 파일 업로드 앤드 포인트 연결
- [x] 변수 이름 및 색 수정 

# Description
- 파일 업로드 관련 서버 엔드 포인트가 생성됨에 따라 클라이언트 기존 코드를 수정하여 연결했습니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-13 12:09 UTC, alswla requested changes
수고하셨습니다 민석님! 변수명 관련 코멘트 하나만 확인 부탁드립니다! 👍

2024-02-13 12:09 UTC, alswla commented on src/App/index.jsx
> +  const hasAwsAudioUrls = audioUrls.mainAudioUrl && audioUrls.subOneAudioUrl;
파일 업로드 기능 추가로 인해 유효성 조건을 변경해 주셨군요 👍

2024-02-13 12:09 UTC, alswla commented on src/components/LandingPage/UploadUrlForm/index.jsx
> +      const response = await axios.post(API.URLS, {
스크럼시 논의했던 endpoint 분리 확인했습니다 👍

2024-02-13 12:09 UTC, alswla commented on src/components/LandingPage/UploadFileForm/index.jsx
> +      const { result } = response.data;
formData를 바로 보내주기 때문에 별도로 zustand 스토어가 필요하지 않은 것 확인했습니다!👍

2024-02-13 12:09 UTC, alswla commented on src/components/LandingPage/UploadFileForm/index.jsx
> +          {files.mainVideoFile?.name || "Upload Main Video"}
파일이 업로드되면 파일명을 보여주시도록 처리해주셨군요! 👍

2024-02-13 12:09 UTC, alswla commented on src/components/LandingPage/UploadFileForm/index.jsx
> +  const [files, setFiles] = useState({
민석님! 해당 부분 `videoFiles`로 명확하게 어떤 종류의 파일인지 적어주는 것도 좋을 것 같습니다! :)
추가로 아래 file도 videoFile로 명확하게 어떤 파일인지 알려주는 것도 좋을 것 같다는 의견입니다! 👍

2024-02-13 13:48 UTC, zzinLee commented on src/App/index.jsx
> +          )
유튜브나 다운로드 어느 쪽이라도 AWS를 거쳐오기 때문에 해당 조건으로 변경해주셨군요 👍

2024-02-13 13:50 UTC, zzinLee commented on src/components/LandingPage/UploadFileForm/index.jsx
> +    console.log(file);
불필요한 로그가 있습니다! 확인 부탁드릴게요~!

```suggestion

```

2024-02-13 13:52 UTC, zzinLee commented on src/components/LandingPage/UploadFileForm/index.jsx
> +    }
여기에도 불필요한 로그가 있는 듯 합니다!
확인 부탁드릴게요~! 

```suggestion
```

2024-02-13 13:53 UTC, zzinLee requested changes
민석님 확인부탁드립니다~!

2024-02-13 15:19 UTC, alswla approved these changes
변경사항 모두 확인했습니다! 수고하셨습니다 민석님!🔥

2024-02-14 02:02 UTC, zzinLee approved these changes

2024-02-14 02:05 UTC, merged