Feat. validation 앤드 포인트 분리 및 영상 다운로드 활성화
KrossCutting/KrossCutting-client pull request #14
Opened 2024-02-18 17:23 UTC by sht02048

# KanBan Title
- [앤드포인트 분리](https://minsug.notion.site/Server-751ffa1efe8444a68fee545c19231a21?pvs=4)

# Tasks in detail - checkList
- [x] 서버 요청을 validations과 compilations로 분리
- [x] 서버에서 전달받은 finalVideoUrl을 전역 상태로 저장 

# Description
- 유저에게 진척상황을 알리기 위해 엔드포인트를 분리하였습니다. 기존에는 하나의 앤드포인트에서 오디오 유효성 검사부터 최종 영상까지 작업했지만 이제 validationa이라는 엔드포인트를 통해 유효성 검사 후 편집을 시작합니다.
- 유저에게 완성된 영상을 다운로드 받을 수 있게 전달받은 s3 url을 이용했습니다.

# Concern
- 서버 요청을 렌더링되는 진척바 페이지에서 하는 것이 아니라 기존 요청을 보냈던 곳에서 다시 보낸 후 응답을 전역 상태로 처리했습니다. 
- 이와 같이 코드를 설계한 이유는 랜더링되는 페이지에서 useEffect를 사용할 시 개발자 모드상태에서 서버 요청이 두번 들어가게 되어 변경했습니다. 만약 실제 배포할때는 useEffect를 사용할지 아니면 이대로 쭉 사용할지 고민이되는데 한번 봐주시면 감사하겠습니다.
- 진척바가 끝까지 채워지지 않는 현상이 있습니다 추후 작업이 필요합니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-18 18:40 UTC, zzinLee commented on src/components/ProcessingPage/EditingPage/index.jsx
> +    enabled: videoStatus,
videoStatus가 Boolean 값으로 보이는데, 변수명이 명사라서 약간의 혼돈이 있을 것 같습니다!
`isVideoInProgress` 등과 같이 컨벤션을 맞춘 변수명이라면 더 가독성이 올라갈 것 같다는 의견입니다 :)

2024-02-18 18:44 UTC, zzinLee commented on src/components/ProcessingPage/EditingPage/index.jsx
> +    }
```suggestion
    if (finalVideoUrl.length) {
      setIsCuttingInProgress(false);
    }
```
또는 
    if (!finalVideoUrl) {
      setIsCuttingInProgress(false);
    }
```
처럼 써도 좋을 것 같다는 의견입니다! 하지만 지금도 명시적이라 좋네요!

2024-02-18 18:46 UTC, alswla requested changes
수고하셨습니다 민석님! 일부 코멘트가 있어 확인 부탁드리겠습니다!🙇‍♀️

2024-02-18 18:46 UTC, alswla commented on src/components/Message/index.jsx
> +            <span className="text-base font-thin md:text-20">{FOOTER}</span>
민석님 해당 부분 span으로 변경하신 이유가 있을까요? 🤔

`<span>` 태그는 특정 텍스트의 일부분에 스타일이나 다른 특별한 특성을 적용할 때 사용된다고 알고 있습니다! (ex. `<p>문단 <span style="color: red;">특정 텍스트</span> 작성시</p>`)

해당 부분의 경우 각 메세지의 HEADER, BODY, FOOTER의 긴 문장에 대해 하나의 문단으로 구조화하여 사용하고 있으므로 `<p>`태그가 보다 적절할 것 같다는 의견입니다!

2024-02-18 18:46 UTC, alswla commented on src/components/ProcessingPage/DownloadBox/index.jsx
> -        </button>
민석님! 해당 부분도 `button`에서 `a` 링크로 변경하신 이유가 있을까요? 이후 다운로드가 필요하다면 button을 통해 서버와 상호작용이 필요할 것 같다는 의견입니다!🤔

2024-02-18 18:46 UTC, alswla commented on src/components/ProcessingPage/ProgressBar/index.jsx
>  };
GET 요청의 응답을 받기까지 `undefined`이기 때문에 `required`시 오류가 나는 부분에 대해 핸들링 해주셨군요 👍

아예 `dafault` 값을 `"start"`로  변경하는것도 좋을 것 같다는 의견입니다! 서버측에서 `"start"`를 전달해주는 미들웨어를 제거하였기 때문에 default로는 `"start"`를주는 것이 더 좋을 것 같다는 의견입니다! (다만 `"start"` 미사용시 삭제해야하고, 그럴 경우 bar 길이가 갑자기 길어질 것 같습니다!)

2024-02-18 18:46 UTC, alswla commented on src/components/ProcessingPage/ProgressBox/index.jsx
> +  progressStatus: "frames",
이부분도 `progressBar`와 동일하게 `"start"`로 `default`주는 것이 좋을 것 같다는 의견입니다!

2024-02-18 18:47 UTC, zzinLee commented on src/components/ProcessingPage/ProgressBar/index.jsx
> +  progressStatus: "frames",
proptypes을 확인하시기 보다는 defaultProps를 쓰시길 선택하셨군요!
다양한 사용으로 오류를 대비하시는 부분이 좋은 것 같아요.

2024-02-18 18:50 UTC, zzinLee requested changes
새로운 endPoint를 확인하고 연결하는 일이 번거로우셨을텐데
고생 많으셨습니다.
코멘트 확인부탁드립니다!

2024-02-19 01:55 UTC, sht02048 commented on src/components/ProcessingPage/EditingPage/index.jsx
> +    enabled: videoStatus,
맞네요 수진님! 해당 값은 `boolean`임으로 `boolean` 컨벤션을 따라 변수명 수정하겠습니다!
```suggestion
    enabled: isEnable,
```

2024-02-19 02:08 UTC, sht02048 commented on src/components/ProcessingPage/EditingPage/index.jsx
> +    }
강제 형 변환은 최대한 지양하는 것이 좋다고 생각하는데 수진님 의견은 어떠신가요? 스크럼 회의때 이야기를 나누어봐도 좋겠네요!

2024-02-19 02:16 UTC, sht02048 commented on src/components/Message/index.jsx
> +            <span className="text-base font-thin md:text-20">{FOOTER}</span>
민지님! 해당 태그가 원래 `<p>`였는데 p 태그는 내부에 아무런 태그도 허용하지 않아서 `span` 태그로 변경했습니다!  
[stackOverflow 참조](https://stackoverflow.com/questions/41928567/div-cannot-appear-as-a-descendant-of-p)

하지만 민지님 말씀대로 `span` 태그는 그 자체로 또다른 목적성을 띄고 있기때문에 div 태그로 변경해놓겠습니다!

2024-02-19 02:17 UTC, sht02048 commented on src/components/ProcessingPage/DownloadBox/index.jsx
> -        </button>
`a` 태그를 통해서 다운로드를 구현했습니다! 
하이퍼링크를 `s3`의 `singedUrl`로 주어 사용자가 클릭시 파일 다운로드가 실행됩니다!

2024-02-19 05:07 UTC, sht02048 commented on src/components/ProcessingPage/ProgressBar/index.jsx
> +  progressStatus: "frames",
`progressStatus`에 리엑트 쿼리의 `data`가 들어가게 되는데 처음 할당되는 `data` 값이 `undefined`이어서 `defaultProps`로 변경하였습니다!

2024-02-19 08:18 UTC, zzinLee commented on src/components/ProcessingPage/EditingPage/index.jsx
> +    }
확인했습니다 :) 이대로 가도 좋을 것 같아요!

2024-02-19 08:19 UTC, zzinLee submitted a review, later dismissed

2024-02-20 02:51 UTC, alswla approved these changes
변경사항 모두 확인했습니다! 수고하셨습니다 민석님!👍

2024-02-20 03:30 UTC, zzinLee approved these changes
앤드포인트 분리하느라 수고 많으셨습니다 민석님~!

2024-02-22 10:20 UTC, merged