Feat. 로딩 컴포넌트 생성 및 임시 마운트 로직 삽입
KrossCutting/KrossCutting-client pull request #5
Opened 2024-02-01 11:53 UTC by sht02048

# KanBan Title
- [로딩 컴포넌트 개발](https://minsug.notion.site/Client-8cf00c9167ef49ebbf7b5400ba60b5eb?pvs=4)

# Tasks in detail - checkList
- [x]  비동기 작업이 시작되자마자 해당 컴포넌트가 렌더링 되도록 합니다
- [x]  비동기 로직 임시 구현 
- [ ]  `fetch` 가 완료될 때까지 로딩 컴포넌트가 계속 렌더링 - **Remarks** 참고

# Description
- svg 파일을 사용하여 로딩 컴포넌트를 생성했습니다.
- `useState`와 `useEffect`를 이용해 조건부 렌더링 로직을 임시로 구현했습니다.

# Remarks
- 추후 서버측 영상 다운로드 로직이 완료된 후에 비동기 로직 완성 필요

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-01 13:45 UTC, alswla requested changes

2024-02-01 13:45 UTC, alswla commented on src/components/LandingPage/MainPage/index.jsx
> +  const [isLoading, setIsLoading] = useState(true);
로딩페이지를 위해 상태를 설정해주셨군요! 상태에 따라 페이지 렌더링을 하는 것은 좋은 것 같습니다! 
다만 `isLoading`의 초기값을 `true`로 설정하신 이유가 있을까요? 🤔

아래 로딩컴포넌틀 렌더링의 경우 [`{isLoading && <Loading />}`](https://github.com/KrossCutting/KrossCutting-client/pull/5/files#diff-391e9bb83396ba73dcddb5095506fb1c4e7327e3ac6253dad1b5f64a54cfcb9cR39) 이 되어서 처음부터 로딩페이지가 나타날 것 같습니다!

2024-02-01 13:45 UTC, alswla commented on src/components/LandingPage/MainPage/index.jsx
> +      setIsLoading(false);
상태의 변수명이 isLoading이기 때문에 로딩중일 경우에 로딩컴포넌트를 띄우는 것이 더 적절하다고 생각하여 초기값을 true로,
로딩이 끝나는 시점에 false로 바꿔주는 것이 좋을 것 같다는 의견입니다! :)

2024-02-01 14:02 UTC, zzinLee commented on src/components/Loading/index.jsx
> +export default Loading;
해당 컴포넌트는 영상을 서버로부터 fetch 해오거나 데이터를 가져오는 과정 중에서 사용 되기 때문에,
`src/components/shared` 에 두고 사용해도 좋을 것 같다는 의견입니다.
확인 부탁드립니다!

2024-02-01 14:06 UTC, zzinLee requested changes
컴포넌트 문서 경로 관련 피드백 확인 부탁드립니다.

2024-02-01 14:07 UTC, sht02048 commented on src/components/LandingPage/MainPage/index.jsx
> +  const [isLoading, setIsLoading] = useState(true);
아직 로딩 상태를 변경하는 로직이 없어서 랜더링 모습을 보여주려고 한건데 `false`로 조정하는 것이 맞는 것 같습니다! 피드백 감사합니다!

2024-02-01 14:10 UTC, sht02048 commented on src/components/Loading/index.jsx
> +export default Loading;
여러 컴포넌트에서 사용되기에 `shared`에 두는게 더 적합하겠네요!

2024-02-01 14:24 UTC, alswla approved these changes
변경사항 모두 확인했습니다! 수고하셨습니다 민석님 👍

2024-02-02 00:56 UTC, zzinLee approved these changes
변경사항 확인했습니다!

2024-02-02 01:04 UTC, merged