Feat. 시작점 선택 페이지 개발
KrossCutting/KrossCutting-client pull request #6
Opened 2024-02-01 13:25 UTC by zzinLee

# KanBan Title
- [시작점 선택 페이지 개발](https://www.notion.so/minsug/Client-a908dcd9b0f74db58f5afa0646741a92?pvs=4)
- [시작점 선택 페이지 - 1분 제한 로직 구현](https://www.notion.so/minsug/Client-1-c1995d008a4b4400adbc9fb37ebd4c6f?pvs=4)

# Tasks in detail - checkList

## 시작점 선택 페이지 개발
- [x]  `AWS S3 url` 로 부터 `mp4` 파일 수신하는 비디오 태그 생성
- [x]  컴포넌트 레이아웃 작성 시, `영상`과 `오디오 시각화 데이터` 가 캐로우 셀 내에 배치
- [x]  상단에 헤더 작성 | 캐로우셀 순서에 맞추어 `Main Video` 와 `Sub Video` 명시
- [x]  첫 렌더링 시 영상 혹은 오디오에서 시작점을 선택할 수 있는 `런타임 선택 버튼`이 등장 하도록 작업
- [x]  `오디오 및 영상 런타임 선택 버튼`을 좌우로 이동하여 원하는 부분을 선택할 수 있도록 작업
- [ ]  `select start` 버튼 | 버튼 클릭 시 해당 런타임에 선택 표기할 수 있도록 작업
- [ ]  `select start` 버튼 | 버튼 클릭 시 해당 런타임 값을 `전역 상태`에 전달
- [ ]  `next step` 버튼 컴포넌트 생성 | 전역상태를 확인하여 시작시간을 모두 받아 온 경우 해당 버튼 생성

## 시작점 선택 페이지 - 1분 제한 로직 구현
- [x]  오디오 컴포넌트의 `UI`를 1분 이상 선택하지 못하도록 제한합니다.
- [x]  비디오 컴포넌트의 `UI`를 1분 이상 선택하지 못하도록 제한합니다.
- [x]  만약 사용자가 선택한 시작점이 1분 이상인 경우, 모달을 띄웁니다.

# Concern
- [비디오와 오디오 연동이 필요하여 store 구조를 변경해야 함](https://github.com/KrossCutting/KrossCutting-client/compare/Feat/startpoint-selection-page?expand=1#diff-6d44cbeada716bdd3bd51d4c8ae9961623e5bb96716147eb608da5f4971753ecR11-R14)을 명시하였습니다.
추후 store 구조를 수정할 예정입니다. 확인부탁드리겠습니다.
- [시작점 1분 제한 로직 구현](https://github.com/KrossCutting/KrossCutting-client/compare/Feat/startpoint-selection-page?expand=1#diff-19d485f24abfb384c648fcf920886fe7a0b55ee2df4c6dcf3905edff7015757cR24-R26)은 사용자가 60초 이상의 시간대를 선택하거나 재생하는 경우, 60초 이후로는 넘어가지 못하도록 고정값을 주었습니다.
- 비디오와 오디오 재생시간 기록을 동시에 연동하고 싶었지만, 어려움이 있어 비디오에서만 선택할 수 있도록 제한하였습니다.

# Description
- 사용자가 url을 입력한 후 렌더링 되는 페이지를 개발하였습니다.
- 사용자는 비디오 재생시간 버튼을 움직여 노래의 시작점을 선택할 수 있도록 안내합니다.

# remarks
- 오디오와 비디오 연동에 문제가 생겨 금일 시간이 소요되었습니다. 금일 칸반 To-do 는 명일 오전 내로 진행할 예정입니다.
- 현재 client 측의 목업을 빠르게 작성하기 위해 `wavesurfer.js`를 사용하였습니다. 
- 추후 `Audio Web API`를 이용하여 `Canvas`에 파형을 그리는 로직을 구현할 예정입니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-01 14:06 UTC, sht02048 requested changes
처음으로 영상과 오디오를 조작하시는 것인데도 기능을 빠르고 정확하게 구현해주신 것 같습니다! 감사합니다 수진님!

2024-02-01 14:06 UTC, sht02048 commented on src/components/startPointSelectionPage/CarouselPage/index.jsx
> +  // TO DO: store 수정 필요
store 수정이 무엇때문에 어떻게 수정이 필요한지 PR Concern에 상세히 적어주셨는데 주석에도 간략히 설명해주시면 추후에 다른 사람이 작업할때 이해하기 수월할 것 같습니다!

2024-02-01 14:06 UTC, sht02048 commented on src/components/startPointSelectionPage/Selectionpage/index.jsx
> +      {/* <StartPointSubmitButton /> */}
주석으로 `To Do` 명시해주시면 좋을 것 같습니다!

2024-02-01 14:06 UTC, sht02048 commented on src/components/startPointSelectionPage/Media/index.jsx
> +        you can choose start point within 60 sec.
문구 잘 짜신 것 같습니다! 추후에 해당 공간에 `alert`를 띄울 수도 있겠네요!

2024-02-01 14:06 UTC, sht02048 commented on src/components/startPointSelectionPage/Media/index.jsx
> +      }
`video duration`이 유한수인지 판별이 필요한 이유를 혹시 알 수 있을까요?

2024-02-01 14:06 UTC, sht02048 commented on src/components/startPointSelectionPage/Media/index.jsx
> +      videoRef.current.removeEventListener("timeupdate", handleAudioTime);
리액트에서 `addEventListener`를 사용하는 것이 조금 어색하게 느껴지는 것 같습니다! `Video` 태그에서 쓸 수 있는 `onTimeUpdate를`  써보는 것에 대해서 어떻게 생각하시나요?

2024-02-01 14:10 UTC, alswla requested changes

2024-02-01 14:10 UTC, alswla commented on src/components/startPointSelectionPage/CarouselPage/index.jsx
> +        <SelectionPage
`SelectionPage`가 `CarouselPage`의 안에 있는 것은 명칭상 어색한 것 같습니다!

페이지라는 변수명을 Container로 변경하는 것에 대해 의견을 나눠보면 좋을 것 같습니다 :)
(`CarouselPage`를 `CarouselContainer`로 변경하고 `SelectionPage`의 경우 `SelectionContainter`로 변경)

2024-02-01 14:10 UTC, alswla commented on src/components/startPointSelectionPage/CarouselPage/index.jsx
> +  const { videoUrls, audioUrls } = useUrlStore();
비디오에서 오디오 연동이 되지 않아 별도로 관리하는 것으로 이해했습니다! 
서버측에서 유효성 검사를 위해 반드시 오디오와 비디오 소스들을 분리하여 저장하므로 두 url을 별도로 저장해도 괜찮을 것 같습니다 :)

내일 스크럼 회의시 스토어 구조에 대해 한번 논의하고, 이후 수정사항 필요시 수정하면 좋을 것 같습니다!

2024-02-01 14:10 UTC, alswla commented on src/components/startPointSelectionPage/Media/index.jsx
> +function Media({ videoSrc, audioSrc }) {
변수명이 너무 광범위한 것 같습니다! MediaPlayers와 같이 보다 자세한 컴포넌트 명이 좋을 것 같다는 의견입니다! 🤔

2024-02-01 14:10 UTC, alswla commented on src/components/startPointSelectionPage/Media/index.jsx
> +      }
1분이상의 선택일 시 영상의 런타임 토글이 이동하지 않도록 고정해주셨군요! 👍

2024-02-01 14:10 UTC, alswla commented on src/components/startPointSelectionPage/CarouselPage/index.jsx
> +          isMain={currentIndex === 0}
`isMain`도 좋지만 `isMainVideo` 혹은 `isMainContent` 같이 자세한 변수명이 좋을 것 같다는 의견입니다! :)

2024-02-02 00:57 UTC, zzinLee commented on src/components/startPointSelectionPage/CarouselPage/index.jsx
> +  // TO DO: store 수정 필요
네 확인했습니다. 추후 반영하여 작업하겠습니다!

2024-02-02 00:57 UTC, zzinLee commented on src/components/startPointSelectionPage/Selectionpage/index.jsx
> +      {/* <StartPointSubmitButton /> */}
확인했습니다!

2024-02-02 01:08 UTC, zzinLee commented on src/components/startPointSelectionPage/Media/index.jsx
> +      }
videoRef.current.duration 이 처리하고 있는 로직은 아래 2가지 경우 입니다.

-  videoRef.current.duration이 NaN 되는 경우 : video 가 없을 때
- videoRef.current.duration이 Infinity가 되는 경우 : 스트리밍과 같은 영상에서 video duration 조회값이 없을 때 

로직 수행 중, 최초 렌더링 시 video 가 조회 되지 않으므로 값이 NaN 이 되는 에러가 발생합니다.
또한 사용자가 스트리밍 url 을 넣을 때 문제가 생길 수 있습니다.

관련 [video태그의 duration property 문서](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration)를 첨부드립니다!

2024-02-02 01:14 UTC, zzinLee commented on src/components/startPointSelectionPage/Media/index.jsx
> +      videoRef.current.removeEventListener("timeupdate", handleAudioTime);
민석님! 좋은 의견 감사합니다.  의견에 대해 조사 해 보니, 
이는 `video` 태그에 명시적으로 전달할 수 이벤트 등록 함수로 보입니다.

하지만, `onTimeUpdate`를 사용하면 useEffect 내부에서 clean-up 함수를 실행하는데에 어려움이 있어보여
`addEventListener`로 사용하고자 하오니 한번 더 확인부탁드리겠습니다 :)

감사합니다.

2024-02-02 01:17 UTC, zzinLee commented on src/components/startPointSelectionPage/CarouselPage/index.jsx
> +        <SelectionPage
좋은 의견입니다! 저 역시 해당 명명이 애매 하다고 느꼈는데, 바로 변경하겠습니다.

2024-02-02 01:18 UTC, zzinLee commented on src/components/startPointSelectionPage/CarouselPage/index.jsx
> +  const { videoUrls, audioUrls } = useUrlStore();
넵 그럼 스크럼 회의 후 store 구조 변경하여 적용하겠습니다 :)

2024-02-02 01:22 UTC, zzinLee commented on src/components/startPointSelectionPage/Media/index.jsx
> +function Media({ videoSrc, audioSrc }) {
MediaPlayer가 적합한 명명으로 생각되어 변경하도록 하겠습니다. 👍

2024-02-02 01:24 UTC, zzinLee commented on src/components/startPointSelectionPage/CarouselPage/index.jsx
> +          isMain={currentIndex === 0}
좋은 의견입니다! 민지님 의견대로 앞에 Media 로 변경하였으니, 
`isMainMedia`로 변경하는 것이 좋을 것 같습니다.
감사합니다.

2024-02-02 01:45 UTC, alswla submitted a review, later dismissed
변경사항 확인했습니다!

2024-02-02 02:51 UTC, sht02048 submitted a review, later dismissed
확인했습니다~

2024-02-02 06:41 UTC, sht02048 approved these changes
변경사항 확인했습니다! 수고하셨어유~

2024-02-02 07:18 UTC, alswla approved these changes
수정사항 확인했습니다! 수고하셨습니다 수진님! 🔥

2024-02-02 07:18 UTC, alswla commented on src/components/LandingPage/UploadForm/index.jsx
> +                className="px-10 mb-10 text-black rounded"
텍스트도 하얗게 나오는부분도 같이 수정해주셨군요! 감사합니다 👍

2024-02-02 07:18 UTC, merged